package com.conways.attendancehelper.db.dao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.conways.attendancehelper.db.dbEntity.AttendanceEntity;
import com.conways.attendancehelper.db.dbEntity.TestEntity;

import com.conways.attendancehelper.db.dao.AttendanceEntityDao;
import com.conways.attendancehelper.db.dao.TestEntityDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig attendanceEntityDaoConfig;
    private final DaoConfig testEntityDaoConfig;

    private final AttendanceEntityDao attendanceEntityDao;
    private final TestEntityDao testEntityDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        attendanceEntityDaoConfig = daoConfigMap.get(AttendanceEntityDao.class).clone();
        attendanceEntityDaoConfig.initIdentityScope(type);

        testEntityDaoConfig = daoConfigMap.get(TestEntityDao.class).clone();
        testEntityDaoConfig.initIdentityScope(type);

        attendanceEntityDao = new AttendanceEntityDao(attendanceEntityDaoConfig, this);
        testEntityDao = new TestEntityDao(testEntityDaoConfig, this);

        registerDao(AttendanceEntity.class, attendanceEntityDao);
        registerDao(TestEntity.class, testEntityDao);
    }
    
    public void clear() {
        attendanceEntityDaoConfig.getIdentityScope().clear();
        testEntityDaoConfig.getIdentityScope().clear();
    }

    public AttendanceEntityDao getAttendanceEntityDao() {
        return attendanceEntityDao;
    }

    public TestEntityDao getTestEntityDao() {
        return testEntityDao;
    }

}
